/*CREATE SCHEMA test AUTHORIZATION sa;*/

CREATE TABLE IF NOT EXISTS userlogin (
ID INT PRIMARY KEY,
username VARCHAR(255), password VARCHAR(255),
role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS employee (
ID INT PRIMARY KEY,
name VARCHAR(255),
salary DOUBLE
);